### ISSUE TITLE
同是在学编译原理，为什么作者能如此优秀😭

### ISSUE THREAD

**Issue by marsvet** [itribs/rcalculator#1]
同是在学编译原理，为什么作者能如此优秀😭

**Comment by itribs** [comment]
看的是极客时间上的课程：编译原理之美，讲的比较通俗易懂，我这才看了第一篇，很多地方写的很粗鲁偷懒

**Comment by marsvet** [comment]
感谢推荐👍，以前还不知道极客时间这个网站，刚看了一下，感觉挺不错的
