### ISSUE TITLE
程序员建议新增hex bin dec 的关键字函数

### ISSUE THREAD

**Issue by heartacker** [itribs/rcalculator#2]
比如hex(123) = 0x7B
方便进行类型转换和获取数据

**Comment by itribs** [comment]
这个可以有，请问dec是什么函数

**Comment by heartacker** [comment]
> 这个可以有，请问dec是什么函数

十进制的意思.

**Comment by itribs** [comment]
已更新，应用中心待审核

**Comment by marsvet** [comment]
dec 好像用不了

**Comment by itribs** [comment]
默认就是十进制，直接输入二进制结果也是十进制
如果是用bin方法后显示二进制，直接bin() * 1就行了

**Comment by marsvet** [comment]
> 默认就是十进制，直接输入二进制结果也是十进制
> 如果是用bin方法后显示二进制，直接bin() * 1就行了
搜嘎，明白了
