### ISSUE TITLE
建议增加运算符

### ISSUE THREAD

**Issue by xxEray** [itribs/rcalculator#3]
建议增加位运算符（如<<, >>, |, &, ^等）和赋值运算符（*=, -=, &=等）。
> 注：这里位运算符的含义分别是：左移、右移、按位或、按位与、按位异或
*********
Title: Suggest Adding Operator
It is recommended to add bitwise operations (<<, >>, |, &, ^, etc.) and increase coincidence operations (*=, -=, &= etc.)
> Note: The meaning of bitwise operators here are: shift left, shift right, bitwise OR, bitwise AND, bitwise XOR

**Comment by itribs** [comment]
已更新
