### ISSUE TITLE
插件建议 是否可以加一个打印字符串功能

### ISSUE THREAD

**Issue by TLocation** [itribs/rcalculator#5]
目前右边直接展示计算结果 需要对应左边的表达式来查看
如果可以做成这样

a = 1
b = 2
//比如
println( "a + b = %d  \r\n" , (a+b) )
//或者
println( "a+b“ )
a + b

**Comment by itribs** [comment]
这样的话一旦print一次\n之后，下面都需要print才能看的懂结果对应，也显的很怪
print("1+2=%d\n", 1+2)  = 1+2=3
3+4                                  = 空一行
print("5+6=%d", 5+6)   = 7
                                         = 5+6=11
就算限制不能输出\n，我暂时还是觉得这个print显的麻烦多余。
如果只是为了方便看对应表达式的话，优化下界面，将表达式右对齐 再加个=号，是不是会比较好呢

**Comment by TLocation** [comment]
提议很好:
表达式右对齐的话编写可能会麻烦点
可以折中表达式还是左对齐 可以画一条虚线来指示当前表达式所对应的结果

**Comment by itribs** [comment]
最近在忙其他项目，都忘了这个了，得等忙完有空了再来改了
